name: football_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio:
  json_annotation: ^4.8.1
  freezed_annotation:
  bloc:
  flutter_bloc:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed:
  build_runner:
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
